version: '3.8'
services:
  db:
    image: postgres
    container_name: postgresql
    
    environment:
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=postgres
      - POSTGRES_DATABASE=postgres
    ports:
      - '5566:5432'
    
    volumes:
      - pgdata:/var/lib/postgresql/data
#add volumn
volumes:
  pgdata: